# Generated by Django 3.0.7 on 2020-06-07 11:39

from django.db import migrations
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20200606_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='my_field',
            field=tinymce.models.HTMLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
