# Generated by Django 3.0.7 on 2020-06-07 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_articles_my_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='my_field',
            new_name='full_story',
        ),
        migrations.RenameField(
            model_name='articles',
            old_name='post',
            new_name='short_story',
        ),
    ]
