# Generated by Django 3.0.7 on 2020-06-07 13:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_remove_articles_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 7, 16, 18, 39, 516293), verbose_name='Publication date'),
        ),
    ]
