# Generated by Django 3.0.7 on 2020-06-07 14:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20200607_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 7, 17, 26, 11, 299244), verbose_name='Publication date'),
        ),
    ]
