# Generated by Django 3.0.7 on 2020-06-07 14:34

import datetime
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20200607_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 6, 7, 17, 34, 15, 692612), verbose_name='Publication date')),
                ('short_story', models.TextField(max_length=300)),
                ('full_story', tinymce.models.HTMLField()),
            ],
        ),
        migrations.DeleteModel(
            name='Articles',
        ),
    ]
