# Generated by Django 3.0.7 on 2020-06-07 17:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_auto_20200607_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 7, 20, 19, 30, 615548), verbose_name='Publication date'),
        ),
    ]
