# Generated by Django 3.0.7 on 2020-06-07 17:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_auto_20200607_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 7, 20, 28, 9, 844808), verbose_name='Publication date'),
        ),
    ]
