# Generated by Django 3.0.7 on 2020-06-07 18:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_auto_20200607_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 7, 21, 1, 26, 226714), verbose_name='Publication date'),
        ),
    ]
