# Generated by Django 3.0.7 on 2020-06-07 20:13

import datetime
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_auto_20200607_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 7, 23, 13, 0, 182699), verbose_name='Publication date'),
        ),
        migrations.AlterField(
            model_name='article',
            name='full_story',
            field=tinymce.models.HTMLField(verbose_name='Full story'),
        ),
        migrations.AlterField(
            model_name='article',
            name='short_story',
            field=models.TextField(max_length=300, verbose_name='Short story'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=160, verbose_name='Title'),
        ),
    ]
