# Generated by Django 3.0.7 on 2020-06-08 16:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_auto_20200607_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 8, 19, 19, 23, 926798), verbose_name='Publication date'),
        ),
    ]
