# Generated by Django 3.0.7 on 2020-06-08 20:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0021_auto_20200608_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 8, 23, 10, 31, 816582), verbose_name='Publication date'),
        ),
    ]
