# Generated by Django 3.0.7 on 2020-06-09 08:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0022_auto_20200608_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 9, 11, 28, 37, 800172), verbose_name='Publication date'),
        ),
    ]
