# Generated by Django 3.0.7 on 2020-06-09 09:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0024_auto_20200609_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 9, 12, 1, 18, 791094), verbose_name='Publication date'),
        ),
    ]
